### ISSUE TITLE
issue when building the project after including the files

### ISSUE THREAD

**Issue by BrsDreamer** [slowriot/libtelegram#19]
hello there. ok so i decided to use your libraries but having issue regarding urdl cuz after including the header files and including 
when i try to run simple echo code i get  errors.

and i properly added the required libraryies still nothing .

target_include_directories(TelegramBotE PUBLIC C:/telegram/include)
target_link_libraries(TelegramBotE PUBLIC -lssl -lcrypto -lboost_system-mt -lboost_date_time-mt -lws2_32)

as you can see im using cmake. so was wondering is this issue with me or something is changed?

thank you very much

note: if it's possible is it ok i get contact address from you like in discord or gitter or something ? that i can chat and properly explain this?

![image](https://user-images.githubusercontent.com/47370192/106094999-41897880-6148-11eb-8c6d-c4f081d4fa5e.png)
![image](https://user-images.githubusercontent.com/47370192/106095668-66cab680-6149-11eb-986b-8591614d37d2.png)

**Comment by slowriot** [comment]
I believe this should be resolved with the latest changes.  Please try the latest version and re-open this issue - or open a new one - if the problem continues.
