### ISSUE TITLE
g++ Boost with OpenSSL

### ISSUE THREAD

**Issue by Guitarmadillo** [slowriot/libtelegram#28]
Hi I'm just hacking my way through this and your documentation did not state OpenSSL in the dependencies. I am not an experienced programmer especially when it comes to getting used to a new interface. 

I first tried to compile without boost installed and got this. 
C:\libtelegram-master\include/libtelegram/config.h:4:10: fatal error: boost/version.hpp: No such file or directory
   4 | #include <boost/version.hpp>

I then succeeded in linking the boost libraries and this is the next error:
C:\boost_1_81_0/boost/asio/ssl/detail/openssl_types.hpp:23:10: fatal error: openssl/conf.h: No such file or directory
   23 | #include <openssl/conf.h>

I then installed 64 bit OpenSSL. I am on Windows 10 trying to compile locally with MinGW. Configured the environment variable paths and added the compiler flags for OpenSSL but no luck so far. 
Any insights are appreciated,

- Christian

**Comment by slowriot** [comment]
The build requirements do not mention secondary dependencies (as in, dependencies of other dependencies), as the list could get rather long, and may change without any changes to this library.  In this case, OpenSSL is a dependency of Boost ASIO: https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/using.html#boost_asio.using.dependencies

It's been a while since I've worked with MinGW, but this stackoverflow answer seems to deal with the specific issue: https://stackoverflow.com/a/39888959/1678468 - for what it's worth, I recall it wasn't particularly complicated to get Boost ASIO building with OpenSSL support on MinGW.  If you built your Boost before you had OpenSSL dev libraries installed on your MinGW system, you may need to rebuild it to enable OpenSSL support.

I'm closing this issue, as building Boost with SSL support is out of scope for this issue tracker, but please feel free to comment if you continue to have issues, and I'll do my best to help you work it out.

**Comment by Guitarmadillo** [comment]
Thank you for the quick response. 

I downloaded boost 1.81 before OpenSSL and understood that it was precompiled. Maybe I need to build it a different way. 

The other thing is regarding the OpenSSL dev libraries. This is the OpenSSL I have downloaded for Windows: https://slproweb.com/products/Win32OpenSSL.html
Maybe since it's a Windows version the file is named differently. 
I first installed OpenSSL version 3.07 and then tried 1.1.1s. 

I added the additional `#include <boost/asio/ssl.hpp>` to one of the examples. The result is the same so far.

**Comment by Guitarmadillo** [comment]
So I got past that issue by downloading a different OPENSSL version. This one in particular: https://github.com/curl/curl-for-win

Now I have been working with the compiler and am getting errors I do not understand. I will provide the compiler line and the errors that follow. 

`C:\SierraChart\ACS_Source>g++ -D _WIN64 -D BOOST_NETWORK_ENABLE_HTTPS=1 -U NOMINMAX -march=x86-64 -mtune=x86-64 -O2 -shared -static  -static-libgcc -static-libstdc++ -s  -fexceptions -std=c++20 echobot.cpp   -IC:\boost_1_81_0 -IC:\OpenSSL\curl-7.86.0_2-win64-mingw\include -IC:\libtelegram-master\include -o C:\SierraChart\ACS_Source\echobot_64.o -Wno-deprecated  -lC:\boost_1_81_0\libs -lC:\OpenSSL\curl-7.86.0_2-win64-mingw\lib -lssl -lcrypto -lboost_system
In file included from C:\libtelegram-master\include/libtelegram/sender.h:10,
                 from C:\libtelegram-master\include/libtelegram/listeners/poll.h:10,
                 from C:\libtelegram-master\include/libtelegram/listener.h:10,
                 from C:\libtelegram-master\include/libtelegram/libtelegram.h:4,
                 from echobot.cpp:3:
C:\libtelegram-master\include/httplib.h:32: warning: "NOMINMAX" redefined
   32 | #define NOMINMAX
      |
In file included from C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/x86_64-w64-mingw32/bits/c++config.h:655,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/iosfwd:38,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/ios:38,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/istream:38,
                 from C:\libtelegram-master\include/urdl/istream.hpp:14,
                 from C:\libtelegram-master\include/libtelegram/listeners/poll.h:7:
C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/x86_64-w64-mingw32/bits/os_defines.h:45: note: this is the location of the previous definition
   45 | #define NOMINMAX 1
      |
In file included from C:\libtelegram-master\include/libtelegram/types/reply_markup/inline_keyboard_markup.h:7,
                 from C:\libtelegram-master\include/libtelegram/types/reply_markup/reply_markup.h:5,
                 from C:\libtelegram-master\include/libtelegram/types/types.h:29,
                 from C:\libtelegram-master\include/libtelegram/listeners/base.h:7,
                 from C:\libtelegram-master\include/libtelegram/listeners/poll.h:9:
C:\libtelegram-master\include/libtelegram/types/reply_markup/inline_keyboard_button.h:16:13: error: expected identifier before ',' token
   16 |     CALLBACK,
      |             ^
C:\libtelegram-master\include/libtelegram/types/reply_markup/inline_keyboard_button.h: In constructor 'telegram::types::reply_markup::inline_keyboard_button::inline_keyboard_button(const std::string&, type, const std::variant<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, telegram::types::callback_game, bool>&)':
C:\libtelegram-master\include/libtelegram/types/reply_markup/inline_keyboard_button.h:53:22: error: expected unqualified-id before ':' token
   53 |   case type::CALLBACK:
      |                      ^
C:\libtelegram-master\include/libtelegram/types/reply_markup/inline_keyboard_button.h: In constructor 'telegram::types::reply_markup::inline_keyboard_button::inline_keyboard_button(const std::string&, const std::string&)':
C:\libtelegram-master\include/libtelegram/types/reply_markup/inline_keyboard_button.h:80:53: error: expected unqualified-id before ',' token
   80 |   : inline_keyboard_button(this_text, type::CALLBACK, content) {
      |                                                     ^
C:\libtelegram-master\include/libtelegram/listeners/poll.h: In static member function 'static void telegram::listener::poll::set_signal_handler()':
C:\libtelegram-master\include/libtelegram/listeners/poll.h:130:22: error: aggregate 'telegram::listener::poll::set_signal_handler()::sigaction signal' has incomplete type and cannot be defined
  130 |     struct sigaction signal;
      |                      ^~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:132:5: error: 'sigemptyset' was not declared in this scope
  132 |     sigemptyset(&signal.sa_mask);
      |     ^~~~~~~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:134:36: error: invalid use of incomplete type 'struct telegram::listener::poll::set_signal_handler()::sigaction'
  134 |     sigaction(SIGINT, &signal, NULL);
      |                                    ^
C:\libtelegram-master\include/libtelegram/listeners/poll.h:130:12: note: forward declaration of 'struct telegram::listener::poll::set_signal_handler()::sigaction'
  130 |     struct sigaction signal;
      |            ^~~~~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h: In static member function 'static void telegram::listener::poll::unset_signal_handler()':
C:\libtelegram-master\include/libtelegram/listeners/poll.h:141:22: error: aggregate 'telegram::listener::poll::unset_signal_handler()::sigaction signal' has incomplete type and cannot be defined
  141 |     struct sigaction signal;
      |                      ^~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:143:5: error: 'sigemptyset' was not declared in this scope
  143 |     sigemptyset(&signal.sa_mask);
      |     ^~~~~~~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:145:36: error: invalid use of incomplete type 'struct telegram::listener::poll::unset_signal_handler()::sigaction'
  145 |     sigaction(SIGINT, &signal, NULL);
      |                                    ^
C:\libtelegram-master\include/libtelegram/listeners/poll.h:141:12: note: forward declaration of 'struct telegram::listener::poll::unset_signal_handler()::sigaction'
  141 |     struct sigaction signal;
      |            ^~~~~~~~~`

**Comment by slowriot** [comment]
Thanks, that's useful.  It looks like there's a clash between the Windows macro `CALLBACK` and the name of an enum type in [libtelegram/types/reply_markup/inline_keyboard_button.h](https://github.com/slowriot/libtelegram/blob/b9c6a0035555099153182f3a6bc17df8111dc902/include/libtelegram/types/reply_markup/inline_keyboard_button.h#L16).  

I've now pushed a change to work around this (https://github.com/slowriot/libtelegram/commit/7440ca85fcdbe102c805d959d8fc6ee12058e78b) - please try the latest version and see if there are any other issues.

**Comment by Guitarmadillo** [comment]
Thank you, that did fix the errors coming from the inline_keyboard_button.h file. 

The following error with **sigaction signal' has incomplete type and cannot be defined
130 | struct sigaction signal;** is still there. 

I will paste what the compiler is throwing but it looks like that first error is causing the rest of them. 

C:\SierraChart\ACS_Source>g++ -D _WIN64 -D BOOST_NETWORK_ENABLE_HTTPS=1 -U NOMINMAX -march=x86-64 -mtune=x86-64 -O2 -shared -static  -static-libgcc -static-libstdc++ -s  -fexceptions  -std=c++20 echobot.cpp  -IC:\boost_1_81_0 -IC:\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include -IC:\OpenSSL\curl-7.86.0_2-win64-mingw\include -IC:\libtelegram-master\include -o C:\SierraChart\ACS_Source\echobot_64.o -Wno-deprecated  -lC:\boost_1_81_0\libs -lC:\OpenSSL\curl-7.86.0_2-win64-mingw\lib -lssl -lcrypto -lboost_system
In file included from C:\libtelegram-master\include/libtelegram/sender.h:10,
                 from C:\libtelegram-master\include/libtelegram/listeners/poll.h:10,
                 from C:\libtelegram-master\include/libtelegram/listener.h:10,
                 from C:\libtelegram-master\include/libtelegram/libtelegram.h:4,
                 from echobot.cpp:3:
C:\libtelegram-master\include/httplib.h:32: warning: "NOMINMAX" redefined
   32 | #define NOMINMAX
      |
In file included from C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/x86_64-w64-mingw32/bits/c++config.h:655,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/csignal:41,
                 from C:\libtelegram-master\include/libtelegram/listeners/poll.h:6:
C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/x86_64-w64-mingw32/bits/os_defines.h:45: note: this is the location of the previous definition
   45 | #define NOMINMAX 1
      |
C:\libtelegram-master\include/libtelegram/listeners/poll.h: In static member function 'static void telegram::listener::poll::set_signal_handler()':
C:\libtelegram-master\include/libtelegram/listeners/poll.h:130:22: error: aggregate 'telegram::listener::poll::set_signal_handler()::sigaction signal' has incomplete type and cannot be defined
  130 |     struct sigaction signal;
      |                      ^~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:132:5: error: 'sigemptyset' was not declared in this scope
  132 |     sigemptyset(&signal.sa_mask);
      |     ^~~~~~~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:134:36: error: invalid use of incomplete type 'struct telegram::listener::poll::set_signal_handler()::sigaction'
  134 |     sigaction(SIGINT, &signal, NULL);
      |                                    ^
C:\libtelegram-master\include/libtelegram/listeners/poll.h:130:12: note: forward declaration of 'struct telegram::listener::poll::set_signal_handler()::sigaction'
  130 |     struct sigaction signal;
      |            ^~~~~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h: In static member function 'static void telegram::listener::poll::unset_signal_handler()':
C:\libtelegram-master\include/libtelegram/listeners/poll.h:141:22: error: aggregate 'telegram::listener::poll::unset_signal_handler()::sigaction signal' has incomplete type and cannot be defined
  141 |     struct sigaction signal;
      |                      ^~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:143:5: error: 'sigemptyset' was not declared in this scope
  143 |     sigemptyset(&signal.sa_mask);
      |     ^~~~~~~~~~~
C:\libtelegram-master\include/libtelegram/listeners/poll.h:145:36: error: invalid use of incomplete type 'struct telegram::listener::poll::unset_signal_handler()::sigaction'
  145 |     sigaction(SIGINT, &signal, NULL);
      |                                    ^
C:\libtelegram-master\include/libtelegram/listeners/poll.h:141:12: note: forward declaration of 'struct telegram::listener::poll::unset_signal_handler()::sigaction'
  141 |     struct sigaction signal;
      |            ^~~~~~~~~

**Comment by slowriot** [comment]
Thanks, this is also helpful.  The errors are due to the default signal handler which attempts to use `sigaction`, which is not available on Windows.  There is already a definition you can set to disable it - `TELEGRAM_NO_SIGNAL_HANDLER`.  I have now also pushed a change to set this define by default when building the examples on Win32, at the CMake stage.

The default signal handler is not an essential component - it's just there to catch ctrl-c from the console, to stop program flow.  Many serious programs would want to override this anyway, with more specific behaviour, so the define is provided to enable that.  You could probably implement a Windows equivalent if you wanted to, or you can choose another way to terminate the program when you want it to end.

Please read the section on signal handlers in the README for more info on this: https://github.com/slowriot/libtelegram#signal-handlers - I have now added a note for Windows users as well.

**Comment by slowriot** [comment]
By the way, as you're just trying to build the example, is there any reason you're not using CMake as per the README?  It should work well on MinGW, and could give you more informative error messages, and save you having to set up a complex set of includes in your commandline.

**Comment by Guitarmadillo** [comment]
Today I got it building the example successfully. Thank you again for the guidance. 

Even after downloading the latest change, I did end up having to define -D TELEGRAM_NO_SIGNAL_HANDLER when building. 

There were some includes I had to slowly work out after that, this is my command line input for building with g++ on my Windows system. It is in a batch file where source and destination are being declared before the compile. 

g++ -D BOOST_NETWORK_ENABLE_HTTPS=1 -D TELEGRAM_NO_SIGNAL_HANDLER -U NOMINMAX -O2 -std=gnu++20  %source%.cpp  -IC:\boost_1_81_0 -IC:\OpenSSL\curl-7.86.0_2-win64-mingw\include -IC:\libtelegram-master\include  -LC:\OpenSSL\curl-7.86.0_2-win64-mingw\lib -o C:\SierraChart\ACS_Source\%exe% -Wno-deprecated -lssl -lcrypto -lcrypt32 -lbcrypt -lwsock32 -lws2_32

Every single one of those -l flags at the end needed to be included, it does not work without them. -lssl also needs to be before -lcrypto which is an easy mistake to make. 

The reason for not using CMake is because I have never used CMake. I started off coding low level logic in a software I use for automated trading. With that interface, a remote compiler is provided. It has only been a short time that I have started doing local compiles to save around 6 seconds of compile time. 

I do have a few questions. 
1. What would be the benefit of using CMake versus the windows command prompt? 
2. Would the CMake build steps provided in your ReadMe be the same for Windows? 

3. Right now the bot can run locally on my PC as long as the program is open and running. Having it run on the system will be good for debugging. When ready I would ideally like to run this program remotely so it can be active 24/7. Do you know of a simple way of doing this? A virtual machine is the only thing I can think of.

**Comment by slowriot** [comment]
> Even after downloading the latest change, I did end up having to define -D TELEGRAM_NO_SIGNAL_HANDLER when building.

Yes, the define is only set for you in CMake by default (so it can easily be overridden if it's not desired) - if you're not using CMake, it wouldn't set automatically.

> -lssl -lcrypto -lcrypt32 -lbcrypt -lwsock32 -lws2_32 ... Every single one of those -l flags at the end needed to be included, it does not work without them. -lssl also needs to be before -lcrypto which is an easy mistake to make.

Thanks, this will hopefully be of help to anyone building on Windows in future!

> What would be the benefit of using CMake versus the windows command prompt?

Not having to manually manage a long commandline for every source file you build; for larger projects, building without some form of build management system becomes very onerous indeed.  There are alternatives, but CMake is the industry standard these days.

> Would the CMake build steps provided in your ReadMe be the same for Windows?

Ideally, yes - although I haven't tested it myself.  Based on what you have reported, the definition in [CMakeLists.txt](https://github.com/slowriot/libtelegram/blob/master/CMakeLists.txt) is likely to require some expansion to link the specific Windows libraries you mentioned.  It could be very helpful if you decide to try it out - if you do, please try modifying the [`set(link_libs)`](https://github.com/slowriot/libtelegram/blob/master/CMakeLists.txt#L23) section, as you mentioned - something like:
```
set(link_libs
  PRIVATE Threads::Threads
  PRIVATE OpenSSL::Crypto
  PRIVATE OpenSSL::SSL
  PRIVATE crypto
  PRIVATE crypt32
  PRIVATE bcrypt
  PRIVATE wsock32
  PRIVATE ws2_32
)
```

> When ready I would ideally like to run this program remotely so it can be active 24/7. Do you know of a simple way of doing this? A virtual machine is the only thing I can think of.

The cheapest way would be on a virtual machine from a cloud hosting provider - something like https://www.hetzner.com/cloud or with AWS.  You may also want to consider packaging your program as a Docker image to make deployment even easier.  

Because these configurations usually work best with Linux, and this is the standard use case for a library such as LibTelegram, all development so far has been on Linux - hence the limited support for Windows so far.  However, if you have good reasons to prefer to use Windows for this application, there's no reason it can't be done - it's just less common.
