### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by moeinsafari** [slowriot/libtelegram#3]
I have this error: 

||=== Build: example_echo in Example: Echo (compiler: GNU GCC Compiler) ===|
include/boost/cgi/fcgi/traits.hpp|12|fatal error: boost/asio/ip/tcp.hpp: No such file or directory|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

where and what is these files ?

**Comment by slowriot** [comment]
Boost Asio is a networking library; it is a dependency for libtelegram.  http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio.html

Download boost at http://www.boost.org.

**Comment by moeinsafari** [comment]
Thank you 👍
