### ISSUE TITLE
Payment Provider Token

### ISSUE THREAD

**Issue by Guitarmadillo** [slowriot/libtelegram#30]
I'm going about testing the payments API and I just wanted to know how exactly would I go about passing the bot payment token? When you connect to a TEST or LIVE payment provider, BotFather gives you a different token. When I try to replace the bot token with that payment token it just fails to connect and the program doesn't run. 

Right now I'm trying to use send_json to send the invoice. I've declared a nlohmann::json type and writing in each parameter from the invoice struct. I am not sure if this is the correct way of doing this. Any help would be appreciated.

**Comment by Guitarmadillo** [comment]
I did get this to work by using the sender.send_json_and_parse to call sendInvoice. 

I created the json object with the necessary fields. Took a lot of troubleshooting to get it with the right format but chatGPT did help. I needed to provide the payment provider token inside of that json along with additional fields. 

This issue can be closed.

**Comment by slowriot** [comment]
I'm glad you resolved your issue.  Can you share an example of the json structure you used for future reference?

**Comment by Guitarmadillo** [comment]
Here is the json object in proper format for sending an invoice. Sorry if the code is messy. 

`if(message.text && *message.text == "/start")
	{
		nlohmann::json prices = nlohmann::json::array({ //json array
			{
				{"label", "product1"},
				{"amount", 150}
			},
			{
				{"label", "product2"},
				{"amount", 250}
			}
		});
		
		 nlohmann::json data = { // json object. 
        {"chat_id", message.chat.id},
        {"title", "Product title"},
        {"description", "Product Description"},
        {"payload", "1es"},
        {"provider_token", "284685063:TEST:NzZjZTgwMjIzMTFk"}, // payment token TEST or LIVE that you get from BotFather after setting up the link to one of the payment providers. 
        {"start_parameter", "invoice1"},
        {"currency", "USD"},
        {"prices", prices}, // all of the variables after this are optional. 
   /*       {"photo_url", "https://example.com/product.jpg"},
        {"photo_size", 100},
        {"photo_width", 100},
        {"photo_height", 100}, 
        {"need_name", true},
        {"need_phone_number", true},
        {"need_email", true},
        {"need_shipping_address", true},
        {"is_flexible", true},
        {"disable_notification", false},
        {"reply_to_message_id", 0}, */
		};
		
		sender.send_json_and_parse<telegram::types::message>("sendInvoice",data);
 
	}`

**Comment by Guitarmadillo** [comment]
Here is the format for the json object to call sendInvoice. Sorry if the code format is not clean. 

nlohmann::json prices = nlohmann::json::array({ //json array
			{
				{"label", "product1"},
				{"amount", 150}
			},
			{
				{"label", "product2"},
				{"amount", 250}
			}
		});
		
		 nlohmann::json data = { // json object. 
        {"chat_id", message.chat.id},
        {"title", "Product title"},
        {"description", "Product Description"},
        {"payload", "1es"}, //string
        {"provider_token", "PaymentToken"}, // payment token TEST or LIVE that you get from BotFather after setting up the link to one of the payment providers. 
        {"start_parameter", "invoice1"}, //string
        {"currency", "USD"},
        {"prices", prices}, // all of the variables after this are optional. 
          {"photo_url", "https://example.com/product.jpg"},
        {"photo_size", 100},
        {"photo_width", 100},
        {"photo_height", 100}, 
        {"need_name", true},
        {"need_phone_number", true},
        {"need_email", true},
        {"need_shipping_address", true},
        {"is_flexible", true},
        {"disable_notification", false},
        {"reply_to_message_id", 0}, 
		};
		
		sender.send_json_and_parse<telegram::types::message>("sendInvoice",data);
