### ISSUE TITLE
boost?

### ISSUE THREAD

**Issue by UnrealKaraulov** [slowriot/libtelegram#32]
For what is needed, if using C++20 language ?

**Comment by slowriot** [comment]
On a high level, Boost is used here primarily for networking, which sadly does not exist in standard C++ as yet.

In terms of specifics , this question can be answered with a simple search: https://github.com/search?q=repo%3Aslowriot%2Flibtelegram%20boost&type=code

At the time of writing, the full Boost depdendency tree for this project is:

- boost/algorithm/string/classification.hpp
- boost/algorithm/string/find.hpp
- boost/algorithm/string/split.hpp
- boost/algorithm/string/trim.hpp
- boost/archive/text_iarchive.hpp
- boost/archive/text_oarchive.hpp
- boost/array.hpp
- boost/asio/basic_io_object.hpp
- boost/asio/buffer.hpp
- boost/asio/connect.hpp
- boost/asio/deadline_timer.hpp
- boost/asio/detail/bind_handler.hpp
- boost/asio/detail/pop_options.hpp
- boost/asio/detail/push_options.hpp
- boost/asio/detail/string_view.hpp
- boost/asio/dispatch.hpp
- boost/asio/error.hpp
- boost/asio.hpp
- boost/asio/io_context.hpp
- boost/asio/io_service.hpp
- boost/asio/ip/address.hpp
- boost/asio/ip/basic_endpoint.hpp
- boost/asio/ip/tcp.hpp
- boost/asio/post.hpp
- boost/asio/read.hpp
- boost/asio/read_until.hpp
- boost/asio/ssl.hpp
- boost/asio/strand.hpp
- boost/asio/streambuf.hpp
- boost/asio/write.hpp
- boost/assert.hpp
- boost/atomic.hpp
- boost/bind.hpp
- boost/cgi/basic_client.hpp
- boost/cgi/basic_connection.hpp
- boost/cgi/basic_request_acceptor.hpp
- boost/cgi/basic_request.hpp
- boost/cgi/common/basic_protocol_service.hpp
- boost/cgi/common/commit.hpp
- boost/cgi/common/connection_base.hpp
- boost/cgi/common/cookie.hpp
- boost/cgi/common/data_map_proxy.hpp
- boost/cgi/common/error.hpp
- boost/cgi/common/form_parser.hpp
- boost/cgi/common/form_part.hpp
- boost/cgi/common/has_hidden_io_service.hpp
- boost/cgi/common/header.hpp
- boost/cgi/common/io_service_provider.hpp
- boost/cgi/common/is_async.hpp
- boost/cgi/common/map.hpp
- boost/cgi/common/name.hpp
- boost/cgi/common/parse_options.hpp
- boost/cgi/common/path_info.hpp
- boost/cgi/common/protocol_traits.hpp
- boost/cgi/common/request_base.hpp
- boost/cgi/common/request_data.hpp
- boost/cgi/common/request_service.hpp
- boost/cgi/common/request_status.hpp
- boost/cgi/common/response.hpp
- boost/cgi/common/role_type.hpp
- boost/cgi/common/source_enums.hpp
- boost/cgi/common/tags.hpp
- boost/cgi/config.hpp
- boost/cgi/connections/anonymous_pipe.hpp
- boost/cgi/connections/shareable_tcp_socket.hpp
- boost/cgi/connections/tcp_socket.hpp
- boost/cgi/detail/basic_io_object.hpp
- boost/cgi/detail/common_headers.hpp
- boost/cgi/detail/extract_params.hpp
- boost/cgi/detail/is_multimap.hpp
- boost/cgi/detail/pop_options.hpp
- boost/cgi/detail/push_options.hpp
- boost/cgi/detail/save_environment.hpp
- boost/cgi/detail/service_base.hpp
- boost/cgi/detail/service_id.hpp
- boost/cgi/detail/throw_error.hpp
- boost/cgi/detail/url_decode.hpp
- boost/cgi/detail/url_decode.ipp
- boost/cgi/error.hpp
- boost/cgi/fcgi/acceptor.hpp
- boost/cgi/fcgi/acceptor_service_impl.hpp
- boost/cgi/fcgi/client.hpp
- boost/cgi/fcgi/error.hpp
- boost/cgi/fcgi/fcgi_connection.hpp
- boost/cgi/fcgi.hpp
- boost/cgi/fcgi/request_acceptor_service.hpp
- boost/cgi/fcgi/request.hpp
- boost/cgi/fcgi/request_service.hpp
- boost/cgi/fcgi/service.hpp
- boost/cgi/fcgi/specification.hpp
- boost/cgi/fcgi/traits.hpp
- boost/cgi/fcgi/transport_selection.hpp
- boost/cgi/fcgi/win32_acceptor_service_impl.hpp
- boost/cgi/fwd/basic_client_fwd.hpp
- boost/cgi/fwd/basic_connection_fwd.hpp
- boost/cgi/fwd/basic_protocol_service_fwd.hpp
- boost/cgi/fwd/basic_request_fwd.hpp
- boost/cgi/fwd/form_parser_fwd.hpp
- boost/cgi/fwd/io_service_provider_fwd.hpp
- boost/cgi/fwd/request_service_fwd.hpp
- boost/cgi/fwd/sessions_fwd.hpp
- boost/cgi/http/status_code.hpp
- boost/cgi/impl/fcgi_request_service.ipp
- boost/cgi/impl/form_parser.ipp
- boost/cgi/impl/response.ipp
- boost/cgi/import/buffer.hpp
- boost/cgi/import/io_service.hpp
- boost/cgi/import/read.hpp
- boost/cgi/import/streambuf.hpp
- boost/cgi/import/write.hpp
- boost/cgi/utility/redirect.hpp
- boost/cgi/utility/sessions.hpp
- boost/config/abi_prefix.hpp
- boost/config/abi_suffix.hpp
- boost/config.hpp
- boost/cstdint.hpp
- boost/detail/workaround.hpp
- boost/filesystem.hpp
- boost/foreach.hpp
- boost/function.hpp
- boost/fusion/include/algorithm.hpp
- boost/fusion/include/at.hpp
- boost/fusion/include/vector.hpp
- boost/fusion/support.hpp
- boost/iostreams/stream.hpp
- boost/lexical_cast.hpp
- boost/logic/tribool.hpp
- boost/mpl/bool.hpp
- boost/mpl/int.hpp
- boost/noncopyable.hpp
- boost/none.hpp
- boost/range.hpp
- boost/ref.hpp
- boost/regex.hpp
- boost/serialization/map.hpp
- boost/serialization/utility.hpp
- boost/shared_ptr.hpp
- boost/static_assert.hpp
- boost/system/error_code.hpp
- boost/system/system_error.hpp
- boost/thread.hpp
- boost/thread/locks.hpp
- boost/thread/lock_types.hpp
- boost/thread/mutex.hpp
- boost/throw_exception.hpp
- boost/tokenizer.hpp
- boost/type_traits/is_same.hpp
- boost/utility/base_from_member.hpp
- boost/utility/enable_if.hpp
- boost/uuid/uuid_generators.hpp
- boost/uuid/uuid.hpp
- boost/uuid/uuid_io.hpp
- boost/version.hpp
