### ISSUE TITLE
Boost seems not to be included

### ISSUE THREAD

**Issue by Spixmaster** [slowriot/libtelegram#8]
I copied the echo.cpp and set the include directory in my project. In the include libtelegram/include/boost almost everything is missing, isn't it?

**Comment by slowriot** [comment]
Yes.  Grab the latest from https://www.boost.org/

**Comment by Spixmaster** [comment]
Thanks but that still does not solve all errors. There are still members of class like "set_callback_message()" that do not work. What am I doing wrong?

**Comment by slowriot** [comment]
set_callback_message() is a function defined by the listeners which inherit from include/libtelegram/listeners/base.h.  Are you including the top-level include, #include <libtelegram/libtelegram.h>?  If you paste the command you're using to build, and the full set of messages you get from the compiler, I might be able to help further.

**Comment by Spixmaster** [comment]
Of course, I included <libtelegram/libtelegram.h>. It seems to me that the library itself want to have access to include files which are not existent.

**Comment by slowriot** [comment]
Which files?  Again, if you paste the command you're using to build and the errors you're actually getting, I might be able to help.

**Comment by Spixmaster** [comment]
1. I put the api in the project folder.
2. I defined where the include files are in my project properties.
3. I copied the source code.

Where is my error?

A picture for you so it may help you understanding me: https://imgur.com/HzTQzmJ

**Comment by Spixmaster** [comment]
I would be very thankful if you could help me. I am trying to figure it out since days.

**Comment by Spixmaster** [comment]
These are errors that occur in the library itself. I did not change anything in the api.
1. https://imgur.com/NgpQRFo
2. https://imgur.com/PgSac3L

**Comment by Spixmaster** [comment]
Even after I have downloaded the boost library and added it, there a many errors on my computer:
https://imgur.com/8xaieg1

**Comment by slowriot** [comment]
This library depends on Boost. Although you still haven't shared your full compiler output, what I can see in your screenshots indicates you haven't included Boost in your project.
